version: 2.1

jobs:
  ui_tests:
    docker:
      - image: your-docker-image-for-ui # Specify the Docker image for UI tests
    working_directory: /app/UI

    steps:
      - checkout

      - run:
          name: Install UI Dependencies
          command: |
            # Install UI-specific dependencies
            npm install

      - run:
          name: Run UI Tests
          command: |
            # Run UI tests command
            npx nightwatch -e chrome

  api_tests:
    docker:
      - image: your-docker-image-for-apis # Specify the Docker image for API tests
    working_directory: /app/APIS

    steps:
      - checkout

      - run:
          name: Install API Dependencies
          command: |
            # Install API-specific dependencies
            npm install

      - run:
          name: Run API Tests
          command: |
            # Run API tests command
            npm test
