version: 2.1

jobs:
  ui_tests:
    working_directory: /Web-QA-Engineer-2023---Technical-Task-/UI

    steps:
      - checkout

      - run:
          name: Install UI Dependencies
          command: |
            # Install UI-specific dependencies
            npm install

      - run:
          name: Run UI Tests
          command: |
            # Run UI tests command
            npx nightwatch -e chrome

  api_tests:
    working_directory: /Web-QA-Engineer-2023---Technical-Task-/APIS

    steps:
      - checkout

      - run:
          name: Install API Dependencies
          command: |
            # Install API-specific dependencies
            npm install

      - run:
          name: Run API Tests
          command: |
            # Run API tests command
            npm test
