version: 2.1

jobs:
  myStore-test:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/project

    steps:
      - checkout

      - run:
          name: List Files in Working Directory
          command: ls -la /home/circleci/project

      - run:
          name: Install Dependencies
          command: npm install
          working_directory: /home/circleci/project/UI

      - run:
          name: Run Nightwatch Tests
          command: npx nightwatch -c /home/circleci/project/UI/nightwatch.conf.js

workflows:
  version: 2
  build:
    jobs:
      - myStore-test
