version: 2.1

jobs:
  ui_tests:
    working_directory: ./UI

    steps:
      - checkout

      - run:
          name: Install UI Dependencies
          command: |
            # Install UI-specific dependencies
            npm install

      - run:
          name: Run UI Tests
          command: |
            # Run UI tests command
            npx nightwatch -e chrome

  api_tests:
    working_directory: ./APIS

    steps:
      - checkout

      - run:
          name: Install API Dependencies
          command: |
            # Install API-specific dependencies
            npm install

      - run:
          name: Run API Tests
          command: |
            # Run API tests command
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - ui_tests
      - api_tests
