version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/project

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Nightwatch Tests
          command: npx nightwatch -e chrome

workflows:
  version: 2
  build:
    jobs:
      - test
