version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  myStore-test:
    docker:
      - image: circleci/node:16
    working_directory: /home/circleci/project

    steps:
      - checkout

      - run:
          name: List Files in Working Directory
          command: ls -la /home/circleci/project

      - run:
          name: Install Dependencies
          command: npm install
          working_directory: /home/circleci/project/UI

      - run:
          name: Run Nightwatch Tests
          command: npx nightwatch 

workflows:
  version: 2
  build:
    jobs:
      - myStore-test
